# Generated by Django 5.2.1 on 2025-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_update',
            new_name='NewsUpdate',
        ),
    ]
