# Generated by Django 5.2.1 on 2025-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_update_newsupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsupdate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
